services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: budgete
      POSTGRES_PASSWORD: budgete
      POSTGRES_DB: budgete
    network_mode: host
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
